# Generated by Django 2.2.12 on 2020-05-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=50)),
                ('lastname', models.CharField(default=None, max_length=50)),
                ('speciality', models.CharField(choices=[('Allergists', 'Allergists'), ('Dermatologists', 'Dermatologists'), ('Ophthalmologists', 'Ophthalmologists'), ('Gynecologists', 'Gynecologists'), ('Cardiologists', 'Cardiologists'), ('Endocrinologists', 'Endocrinologists'), ('Gastroenterologists', 'Gastroenterologists'), ('Nephrologists', 'Nephrologists'), ('Urologists', 'Urologists'), ('Pulmonologists', 'Pulmonologists'), ('Otolaryngologists', 'Otolaryngologists'), ('Neurologists', 'Neurologists'), ('Psychiatrists', 'Psychiatrists'), ('Oncologists', 'Oncologists'), ('Radiologists', 'Radiologists'), ('Rheumatologists', 'Rheumatologists'), ('General surgeons', 'General surgeons'), ('Orthopedic surgeons', 'Orthopedic surgeons'), ('Cardiac surgeons', 'Cardiac surgeons'), ('Anesthesiologists', 'Anesthesiologists')], max_length=50)),
                ('address', models.CharField(default=None, max_length=500)),
                ('emailID', models.EmailField(default=None, max_length=200)),
                ('phone', models.CharField(default=None, max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=30)),
                ('userInstance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hms1.DoctorRegister')),
            ],
        ),
    ]
