# Generated by Django 2.2.12 on 2020-05-23 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordatabase',
            name='userInstance',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hms1.DoctorRegister'),
        ),
    ]
