# Generated by Django 2.2.12 on 2020-05-23 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms1', '0002_auto_20200524_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=50)),
                ('lastname', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=500)),
                ('emailID', models.EmailField(default=None, max_length=200)),
                ('phone', models.CharField(default=None, max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50)),
                ('locationadd', models.CharField(default=None, max_length=500)),
                ('sickdetail', models.CharField(default=None, max_length=500)),
                ('userInstance', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hms1.PatientRegister')),
            ],
        ),
    ]
