# Generated by Django 2.2.12 on 2020-05-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms1', '0003_patientdatabase_patientregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordatabase',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='doctordatabase',
            name='emailID',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctordatabase',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctordatabase',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctordatabase',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='doctordatabase',
            name='speciality',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctordatabase',
            name='userInstance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hms1.DoctorRegister'),
        ),
    ]
