# Generated by Django 2.2.12 on 2020-05-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms1', '0004_auto_20200524_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordatabase',
            name='speciality',
            field=models.CharField(choices=[('Allergists', 'Allergists'), ('Dermatologists', 'Dermatologists'), ('Ophthalmologists', 'Ophthalmologists'), ('Gynecologists', 'Gynecologists'), ('Cardiologists', 'Cardiologists'), ('Endocrinologists', 'Endocrinologists'), ('Gastroenterologists', 'Gastroenterologists'), ('Nephrologists', 'Nephrologists'), ('Urologists', 'Urologists'), ('Pulmonologists', 'Pulmonologists'), ('Otolaryngologists', 'Otolaryngologists'), ('Neurologists', 'Neurologists'), ('Psychiatrists', 'Psychiatrists'), ('Oncologists', 'Oncologists'), ('Radiologists', 'Radiologists'), ('Rheumatologists', 'Rheumatologists'), ('General surgeons', 'General surgeons'), ('Orthopedic surgeons', 'Orthopedic surgeons'), ('Cardiac surgeons', 'Cardiac surgeons'), ('Anesthesiologists', 'Anesthesiologists')], max_length=50),
        ),
    ]
