# Generated by Django 2.2.12 on 2020-05-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms1', '0005_auto_20200524_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdatabase',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='patientdatabase',
            name='emailID',
            field=models.EmailField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='patientdatabase',
            name='firstname',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='patientdatabase',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patientdatabase',
            name='lastname',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='patientdatabase',
            name='locationadd',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='patientdatabase',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='patientdatabase',
            name='sickdetail',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
    ]
