# Generated by Django 2.2.12 on 2020-05-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms1', '0006_auto_20200524_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdatabase',
            name='userInstance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hms1.PatientRegister'),
        ),
    ]
