# Generated by Django 2.2.12 on 2020-05-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms1', '0008_receptionistdatabase_receptionistregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HRDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=20)),
                ('lastname', models.CharField(default=None, max_length=20)),
                ('address', models.CharField(default=None, max_length=500)),
                ('emailID', models.CharField(default=None, max_length=200)),
                ('phone', models.CharField(default=None, max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default=None, max_length=100)),
                ('userInstance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hms1.HRRegister')),
            ],
        ),
    ]
