# Generated by Django 2.2.12 on 2020-05-25 05:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms1', '0009_hrdatabase_hrregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=50)),
                ('Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('AP', 'Approved'), ('RJ', 'rejected')], default='PD', max_length=2)),
                ('message', models.CharField(default='Pending Approval', max_length=1000)),
                ('Doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hms1.DoctorDatabase')),
            ],
        ),
    ]
